### PR TITLE
Fix #29 - allow MapLibre GL JS to move to any latitude

### LINKED ISSUE #29: Maplibre-gl-leaflet layer is mis-aligned with map when panning the map off screen
If you drag the map out of the window, the maplibre-gl-leaflet layer gets stuck in view while other leaflet layers (like markers) continue to get pulled, causing the two layers not to be aligned correctly. 

## Replication case

https://jsbin.com/vepuyeqoyo/3/edit?html,output

1. Open the demo case
2. Drag the map down
    - **Expected**: point stays in its place relative the maplibre-gl-leaflet layer (in the ocean above greenland)
    - **Actual**: when the maplibre-gl-leaflet layer reaches the bottom of the window, as the map continues to be drug down, the point moves relative to the maplibre-gl-leaflet layer, moving all the way off screen.

https://user-images.githubusercontent.com/209355/184433968-8462d8ce-71c6-4628-96d6-02ee44dd1a67.mp4

### PR DESCRIPTION
**Pull request by patrickarlt**
Turns out all we needed to do to fix #29 was allow MapLibre to move the map to any latitude. This also includes a debug folder with an example.

### CODE REVIEW

**Comment by gavinr** [comment]
Looks great! :+1:

**Comment by wipfli** [comment]
Thanks for taking the time to submit this pull request. I tested it locally and the map and the marker keep the same relative displacement, so it seems to solve the problem in #29.

What I am worried about is the change in behavior that users can now pan the map out of the viewport. Do you think this is problematic?

**Comment by patrickarlt** [comment]
> What I am worried about is the change in behavior that users can now pan the map out of the viewport. Do you think this is problematic?

@wipfli as weird as it is this is actually the expected behavior in Leaflet. I just checked and if you go to the homepage and zoom out all the way you can pan the world right out of the screen. So I think this aligns with the default Leaflet behavior. If a user wants to limit it they can use `map.setMaxBounds()` in Leaflet to limit it.

**Comment by wipfli** [comment]
You are right @patrickarlt

**Review by wipfli — APPROVED** [review]
Since this is what leaflet does, I think it is good to go. Thanks for the contribution @patrickarlt!

**Comment by wipfli** [comment]
We forgot the changelog item. Do you mind adding an item in a follow-up pull request @patrickarlt?

**Pull request merged**
