### PR TITLE
round CSS translate values to avoid blurry tiles

### PR DESCRIPTION
**Pull request by ma7moudat**
Fixes https://github.com/maplibre/maplibre-gl-leaflet/issues/41

### CODE REVIEW

**Comment by lseelenbinder** [comment]
This looks good to me. Were you able to confirm it doesn't affect geographic correctness? For example, alignment with other layers and and markers?

**Comment by ma7moudat** [comment]
> This looks good to me. Were you able to confirm it doesn't affect geographic correctness? For example, alignment with other layers and and markers?

I think that would require someone with better geolocation experience who understands the ramifications of this optimised positioning.

For my use-case it's an acceptable compromise to have slight inaccuracy in exchange of a sharp map.

Do you have any suggestions on how to test it? Or should we maybe make the optimised positioning an optional feature maybe?

**Comment by lseelenbinder** [comment]
After further thought, I don't think this can introduce errors, since you can't visually determine a sub-pixel layout difference (by definition).

**Review by lseelenbinder — APPROVED** [review]

**Comment by ma7moudat** [comment]
Hi @lseelenbinder,
Could you please make sure 0.0.19 has been published to npm?
Last time you said you weren't sure who in charge of that, but I have no one else to turn to. Sorry 😅

**Comment by wipfli** [comment]
If we find out how to make a release, let us document the steps in a RELEASE.md file...

**Comment by lseelenbinder** [comment]
@wipfli we just need to tag it. :)


@ma7moudat  I was initially hoping to get the typescript stuff better fixed, and then didn't get it resolved, and then it all got lost in the shuffle. I'll try to get this out today or tomorrow--or @wipfli could do it if he has a chance before I do.

**Comment by ma7moudat** [comment]
Hi @lseelenbinder & @wipfli and happy new year :)

Unfortunately, it seems that the latest changes still weren't published to npm. Could you please take care of it?

Sorry for all the nagging, but we really need this fix :|

Thanks

**Comment by wipfli** [comment]
Happy new year

**Comment by lseelenbinder** [comment]
@ma7moudat It was published, earlier today. Sorry for the delay!

**Pull request merged**
