### PR TITLE
add maplibre-gl-js 3.x.x to peerDependencies

### LINKED ISSUE #50: support for maplibre-gl 3.x
Hi, 
firstly, thanks for maintaining this!

This package currently lists ` "maplibre-gl": "^2.4.0"` as peer dependency. Is there anything stopping it from moving to 3.x ?

### PR DESCRIPTION
**Pull request by goapunk**
I only did some simple manual testing, so far it seems to work with 3.3.1

fixes #50

### CODE REVIEW

**Review by lseelenbinder — APPROVED** [review]
LGTM

**Comment by goapunk** [comment]
@lseelenbinder thanks for merging! Are there any plans to publish a new release soon? :)

**Comment by wipfli** [comment]
Maybe you can create a pull request for the release @goapunk ? Here seems to be some documentation https://github.com/maplibre/maplibre-gl-leaflet/blob/main/CONTRIBUTING.md

**Comment by goapunk** [comment]
@wipfli will have a look

**Comment by lseelenbinder** [comment]
Just deployed those changes @goapunk. Thanks for the PRs!

**Pull request merged**
